name: gobuild
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  gobuild:
    name: gobuild
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: go build -o app