name: npmbuild
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  npmbuild:
    name: npminstall
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
          check-latest: true
      - name: Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build